service: too-good-to-go-bot
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x

functions:
  login:
    handler: src/Lambdas/LoginLambda.handler
    url: true
    events:
      - httpApi: '*'


plugins:
  - serverless-plugin-typescript